#!/usr/bin/env python3
"""gen_golden_from_gribtract.py — Generate gribtract golden reference JSON using gribtract decoder.

This script uses gribtract's decode command to extract GRIB2 metadata and data values,
then transforms it into the golden JSON format expected by the differential test suite.

Usage:
    python3 scripts/gen_golden_from_gribtract.py <grib2_file> <fixture_id> [--output-dir DIR]

Output:
    tests/corpus/golden/<fixture_id>.json

Requirements:
    - gribtract CLI must be built and available via `cargo run --bin gribtract -- decode`
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime


def run_gribtract_decode(grib2_path):
    """Run gribtract decode and return parsed data.

    Args:
        grib2_path: Path to GRIB2 file

    Returns:
        Parsed JSON data from gribtract decode

    Raises:
        subprocess.CalledProcessError: If gribtract fails
        ValueError: If gribtract output is not valid JSON
    """
    try:
        # Run gribtract decode command
        result = subprocess.run(
            ['cargo', 'run', '--bin', 'gribtract', '--', 'decode', str(grib2_path)],
            capture_output=True,
            text=True,
            check=True,
            cwd='/home/coding/gribtract'
        )

        # Debug output goes to stderr, JSON goes to stdout
        # Just parse stdout directly
        return json.loads(result.stdout)

    except subprocess.CalledProcessError as e:
        print(f"ERROR: gribtract decode failed: {e}", file=sys.stderr)
        if e.stderr:
            print(f"gribtract stderr: {e.stderr}", file=sys.stderr)
        raise

    except json.JSONDecodeError as e:
        print(f"ERROR: Failed to parse gribtract JSON output: {e}", file=sys.stderr)
        print(f"gribtract stdout: {result.stdout[:500]}...", file=sys.stderr)
        raise ValueError(f"Invalid JSON from gribtract: {e}")


def gen_golden_from_gribtract(grib2_path, fixture_id, output_dir):
    """Generate golden JSON using gribtract decoder.

    Args:
        grib2_path: Path to input GRIB2 file
        fixture_id: Fixture ID for output filename
        output_dir: Directory for output JSON

    Raises:
        SystemExit: On file access or parsing errors
    """
    grib2_path = Path(grib2_path)

    if not grib2_path.exists():
        print(f"ERROR: GRIB2 file not found: {grib2_path}", file=sys.stderr)
        sys.exit(1)

    # Run gribtract decode and get JSON
    try:
        fields_data = run_gribtract_decode(grib2_path)
    except (subprocess.CalledProcessError, ValueError) as e:
        print(f"ERROR: Failed to extract data from {grib2_path}: {e}", file=sys.stderr)
        sys.exit(1)

    # Check for fields
    if not fields_data or not isinstance(fields_data, list):
        print(f"ERROR: No fields found in gribtract output", file=sys.stderr)
        sys.exit(1)

    # Transform gribtract output to golden format
    for field in fields_data:
        # Transform forecast_time -> forecast
        if 'forecast_time' in field:
            field['forecast'] = field.pop('forecast_time')

        # Transform parameter_id -> parameter
        if 'parameter_id' in field:
            field['parameter'] = field.pop('parameter_id')

        # Transform values format: {"type": "dense", "data": [...]} -> {"Dense": [...]}
        if 'values' in field and isinstance(field['values'], dict):
            if 'data' in field['values']:
                field['values'] = {'Dense': field['values']['data']}

        # Remove any extra fields not in golden format
        # (e.g., unix_seconds, offset_seconds, valid_unix_seconds)
        if 'forecast' in field and 'reference_time' in field['forecast']:
            ref_time = field['forecast']['reference_time']
            # Remove unix_seconds if present
            ref_time.pop('unix_seconds', None)
        if 'forecast' in field:
            field['forecast'].pop('offset_seconds', None)
            field['forecast'].pop('valid_unix_seconds', None)

    # Build golden file structure
    golden = {
        'fixture_id': fixture_id,
        '_provenance': (
            f'Generated by scripts/gen_golden_from_gribtract.py from {grib2_path.name}'
            ' using gribtract pure-Rust GRIB2 decoder (cargo run --bin gribtract -- decode).'
        ),
        'fields': fields_data,
        'parser_version': 'gribtract_pure_rust_1.0'
    }

    # Write output
    out_path = Path(output_dir) / f'{fixture_id}.json'
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path, 'w') as f:
        json.dump(golden, f, indent=4)

    print(f'Written: {out_path}  ({len(fields_data)} field(s))')


def main():
    parser = argparse.ArgumentParser(
        description='Generate gribtract golden reference JSON from a GRIB2 file using gribtract decoder'
    )
    parser.add_argument('grib2_file', help='Input GRIB2 file')
    parser.add_argument('fixture_id', help='Fixture ID (becomes the output filename)')
    parser.add_argument(
        '--output-dir',
        default='tests/corpus/golden',
        help='Directory for the output JSON (default: tests/corpus/golden)',
    )
    args = parser.parse_args()

    gen_golden_from_gribtract(args.grib2_file, args.fixture_id, args.output_dir)


if __name__ == '__main__':
    main()
